# Generated by Django 3.0.3 on 2020-02-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='community',
        ),
    ]
