# Generated by Django 3.0.3 on 2020-02-11 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_comment_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(related_name='community_moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
